### ISSUE TITLE
In Surface

### ISSUE THREAD

**Issue by bgranzow** [ibaned/gmodel#3]
Gmsh supports embedding points and lines in surfaces and surfaces in volumes.

search for "In Surface" in the page:
http://gmsh.info/doc/texinfo/gmsh.html

It would be cool if this capability was reflected in the Gmodel interface, specifically so that .dmg files recognize these embedded geometric entities.

**Comment by ibaned** [comment]
I'm a bit swamped hence the lack of response, but basically this is tricky to implement because until now faces were only adjacent to loops. we could either throw lines and points into the adjacent objects vector and have logic to check whether each item is something other than a loop, or we could introduce other vectors for the embedded objects. I'm actually somewhat in favor of the first option, because it leaves certain graph algorithms intact.

**Comment by bgranzow** [comment]
This is not urgent at all. I am unsure of how to best implement this, but I would like to point out that I was able to successfully put a point into a surface by 'post-processing' the output .geo and .dmg file from gmodel here:

https://github.com/bgranzow/Troy-Meshes/blob/master/square_in_square/geom.geo#L39
https://github.com/bgranzow/Troy-Meshes/blob/master/square_in_square/geom.dmg

APF/GMI were able to read this mesh and model just fine it seems.

**Comment by ibaned** [comment]
That brings up an interesting point. Is the DMG file unmodified ? I'm fairly sure that format doesn't support this. On the other hand, it is unlikely to be an issue... just something extra to keep in mind.

**Comment by bgranzow** [comment]
I had to manually insert a new geometric vertex into the DMG file.
*edit: in this line here:
https://github.com/bgranzow/Troy-Meshes/blob/master/square_in_square/geom.dmg#L12

**Comment by ibaned** [comment]
I just implemented this in commit e3384fe. See the "line_in_cube" test for a usage example.
